ADMIN_KEY=""

[general]
MONGODB_URI=""
UMAMI_WEBSITE_ID=""
YOUTUBE_VIDEO_ID=""

[api_key]
NEWS_API_KEY=""
TMDB_API_KEY=""
NASA_API_KEY=""
GEMINI_API_KEY=""
OpenAI_API_KEY=""
WEATHER_API_KEY=""
YOUTUBE_API_KEY=""
UBERDUCK_API_KEY=""
SPOONACULAR_API_KEY=""

[brainTumorModel]
BRAIN_TUMOR_TEST="134WXQnPC898sVM2R04uWCDv89qmkUlrU"

[depressionDetectionModel]
DEPRESSION_DETECT="13eQ5VTHpUXPSYDPN6d48ORG444v0oH1W"

[diabetesDetectionModel]
DIABETES_TEST_MODEL="1TGnEotkDMgfpWi-y2xDx2GMje9ilhmiq"

[digitRecognizerModel]
MODEL_9="10xPlPWhBA57qlDInCBJ7Ay9bNKcaIB7y"
MODEL="1-14pBK3rEEqL5dEB6vt4rj2VG2afRfw9"

[maskDetectionModel]
DEPLOY="15EIN6Zz1rOtNKuhKsDSEeQ6yDJ2EQqFi"
MASKCHECK="147gm-vw2a5W0XegVHYf9yVJqLVko9xW-"
RES10_300x300_SSD_ITER_140000="1X7CNEP6isgN8GKHiDkmhyZInfLr1hnJE"

[movieRecommendationModel]
SIMILARITY="190cu1pN2yJU7UcP5lGAcTMvOd1O1WJta"
MOVIES_LIST="1MlnqIHqbcuPaogV9LzotmR0Eyelju4TV"

[objectDetectionModel]
YOLO11S="1z9X2yvEaTThV6JBVkPRMLakh1O5KM4cl"
YOLOV8S="1s3abY6DUaIE0w54F9Bq-HbcTkiruvbZn"
